Require googletrans-4.0.0rc1 to fix autotranslate
With googletrans-3.0.0 I had the following error:
AttributeError: 'NoneType' object has no attribute 'group'
See https://github.com/ssut/py-googletrans/issues/366 - requiring
4.0.0rc1 fixed it.