Exchange googletrans to fix failing tests
The googletrans module hasn't been updated for a longer while. Our tests
are failing because googletrans is still using an outdated version of
httpx. Error is
AttributeError: module 'httpcore' has no attribute 'SyncHTTPTransport'
Fixing this by using the temporary googletrans-py module:
https://pypi.org/project/googletrans-py/